### ISSUE TITLE
The build.sh doesn't work correctly

### ISSUE THREAD

**Issue by AlexRudenko50** [Lauszus/fftw3-android#2]
Hi, I am Alex Rudenko 
As a new user of this project, I tried to build this project as Readme file mentioned.
I've installed android NDK and executed build.sh file on Windows 
but it shows an error like below
bash: rev : command not found
To solve this issue, should I have to install cygwin to windows ?
As some documents mentioned, it doesn't need to install cygwin because newest android studio version support android GNU compiler.
If so, is there any other way to build it on android studio?
Looking forward to your reply
Best
Alex

**Comment by Lauszus** [comment]
@AlexRudenko50 this simple that you do not have the ```rev``` program installed. 

Are you on Windows 10? If so then I would recommend getting Windows Subsystem for Linux: https://docs.microsoft.com/en-us/windows/wsl/install-win10. You can also try to cygwin to get the necessary tools.

**Comment by AlexRudenko50** [comment]
Thanks for your reply
This answer is very helpful.
I've fixed the issue by your help.
Thanks again
